#!/bin/bash
# Because while I am smart enough to compose this entire file from the
# command line using echo statements, I am not, in fact, smart enough to
# figure out how to make minitest easily autorun the entire spec suite when
# in minitest/spec mode. LOL/dumb
echo "find spec -type f | xargs ruby"
find spec -type f | xargs ruby
